# Generated by Django 5.2.1 on 2025-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_analysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
